namespace:
  name: prod
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: deviesadocker/techtrends
  tag: latest
  pullPolicy: Always
replicaCount: 5
resources:
  requests: 
    memory: 128Mi
    CPU: 350m
  limits: 
    memory: 128Mi
    CPU: 500m
container: 
  port: 3111
  protocol: TCP
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz